(function (root) {
  'use strict';

  const SKILLS = [
    // --- Languages ---
    { name: 'JavaScript', aliases: ['js', 'ecmascript'] },
    { name: 'TypeScript', aliases: ['ts'] },
    { name: 'Python' },
    { name: 'Java' },
    { name: 'C', pattern: /(?<![A-Za-z+#.])C(?![A-Za-z+#])/ },
    { name: 'C++', pattern: /C\+\+/ },
    { name: 'C#', pattern: /C#/ },
    { name: 'Go', pattern: /(?<![A-Za-z])Go(?:lang)?(?![a-z])/ },
    { name: 'Rust' },
    { name: 'Ruby' },
    { name: 'PHP' },
    { name: 'Swift' },
    { name: 'Kotlin' },
    { name: 'Scala' },
    { name: 'Perl' },
    { name: 'R', pattern: /(?<![A-Za-z.])R(?:\s*[,/;)]|\s+(?:and|or|programming|language|scripts?|packages?|shiny)\b)/ },
    { name: 'MATLAB' },
    { name: 'Objective-C' },
    { name: 'Dart' },
    { name: 'Elixir' },
    { name: 'Erlang' },
    { name: 'Haskell' },
    { name: 'Clojure' },
    { name: 'Groovy' },
    { name: 'Lua' },
    { name: 'Shell scripting', aliases: ['shell script', 'shell scripts'] },
    { name: 'Bash' },
    { name: 'PowerShell' },
    { name: 'VBA' },
    { name: 'COBOL' },
    { name: 'Fortran' },
    { name: 'Assembly' },
    { name: 'Solidity' },
    { name: 'Julia' },
    { name: 'F#', pattern: /F#/ },
    { name: 'Visual Basic' },
    { name: 'Delphi' },
    { name: 'Apex' },
    { name: 'ABAP' },
    { name: 'SAS' },
    { name: 'SPSS' },
    { name: 'Stata' },

    // --- Front end ---
    { name: 'HTML', aliases: ['html5'] },
    { name: 'CSS', aliases: ['css3'] },
    { name: 'Sass', aliases: ['scss'] },
    { name: 'Less' },
    { name: 'Tailwind CSS', aliases: ['tailwind'] },
    { name: 'Bootstrap' },
    { name: 'React', pattern: /(?<![A-Za-z0-9])React(?:\.js|js)?(?!\s*Native)(?![A-Za-z0-9])/i },
    { name: 'Angular', aliases: ['angularjs'] },
    { name: 'Vue.js', aliases: ['vue', 'vuejs'] },
    { name: 'Svelte', aliases: ['sveltekit'] },
    { name: 'Next.js', aliases: ['nextjs'] },
    { name: 'Nuxt.js', aliases: ['nuxt'] },
    { name: 'Remix' },
    { name: 'Ember.js', aliases: ['ember'] },
    { name: 'Backbone.js', aliases: ['backbone'] },
    { name: 'jQuery' },
    { name: 'Redux' },
    { name: 'MobX' },
    { name: 'RxJS' },
    { name: 'Webpack' },
    { name: 'Vite' },
    { name: 'Babel' },
    { name: 'ESLint' },
    { name: 'Storybook' },
    { name: 'Three.js', aliases: ['threejs'] },
    { name: 'D3.js', aliases: ['d3'] },
    { name: 'WebGL' },
    { name: 'WebAssembly', aliases: ['wasm'] },
    { name: 'Web Components' },
    { name: 'Material UI', aliases: ['mui'] },
    { name: 'Chakra UI' },
    { name: 'Figma' },
    { name: 'Accessibility', aliases: ['wcag', 'a11y', 'section 508'] },
    { name: 'Responsive design' },

    // --- Mobile ---
    { name: 'React Native' },
    { name: 'Flutter' },
    { name: 'SwiftUI' },
    { name: 'UIKit' },
    { name: 'Android SDK', aliases: ['android development'] },
    { name: 'Jetpack Compose' },
    { name: 'Xamarin' },
    { name: 'Ionic' },
    { name: 'Cordova' },
    { name: 'iOS development', aliases: ['ios'] },

    // --- Backend and frameworks ---
    { name: 'Node.js', aliases: ['node', 'nodejs'] },
    { name: 'Express.js', aliases: ['express', 'expressjs'] },
    { name: 'NestJS', aliases: ['nest.js'] },
    { name: 'Deno' },
    { name: 'Spring', pattern: /(?<![A-Za-z0-9])Spring(?!\s*Boot)(?![A-Za-z0-9])/i },
    { name: 'Spring Boot' },
    { name: 'Hibernate' },
    { name: 'JPA' },
    { name: 'Jakarta EE', aliases: ['java ee', 'j2ee'] },
    { name: 'Micronaut' },
    { name: 'Quarkus' },
    { name: 'Django' },
    { name: 'Flask' },
    { name: 'FastAPI' },
    { name: 'Ruby on Rails', aliases: ['rails'] },
    { name: 'Sinatra' },
    { name: 'Laravel' },
    { name: 'Symfony' },
    { name: 'CodeIgniter' },
    { name: 'ASP.NET', aliases: ['asp.net core'] },
    { name: '.NET', pattern: /\.NET(?!\s*Core)\b/i },
    { name: '.NET Core', pattern: /\.NET\s*Core\b/i },
    { name: 'Entity Framework' },
    { name: 'Gin' },
    { name: 'Phoenix' },
    { name: 'Play Framework' },
    { name: 'Akka' },
    { name: 'Netty' },
    { name: 'gRPC' },
    { name: 'GraphQL' },
    { name: 'REST APIs', aliases: ['rest', 'restful', 'rest api'] },
    { name: 'SOAP' },
    { name: 'OpenAPI', aliases: ['swagger'] },
    { name: 'WebSockets', aliases: ['websocket'] },
    { name: 'Protocol Buffers', aliases: ['protobuf'] },
    { name: 'Thrift' },

    // --- Databases ---
    { name: 'SQL', pattern: /(?<![A-Za-z0-9])SQL(?!\s*Server)(?![A-Za-z0-9])/i },
    { name: 'MySQL' },
    { name: 'PostgreSQL', aliases: ['postgres'] },
    { name: 'SQL Server', aliases: ['mssql', 't-sql', 'tsql'] },
    { name: 'Oracle Database', aliases: ['oracle', 'pl/sql', 'plsql'] },
    { name: 'SQLite' },
    { name: 'MariaDB' },
    { name: 'MongoDB', aliases: ['mongo'] },
    { name: 'Cassandra' },
    { name: 'DynamoDB' },
    { name: 'Redis' },
    { name: 'Memcached' },
    { name: 'Elasticsearch', aliases: ['elastic search'] },
    { name: 'OpenSearch' },
    { name: 'Solr' },
    { name: 'Neo4j' },
    { name: 'CouchDB' },
    { name: 'Firestore' },
    { name: 'Firebase' },
    { name: 'Snowflake' },
    { name: 'Redshift' },
    { name: 'BigQuery' },
    { name: 'Databricks' },
    { name: 'Teradata' },
    { name: 'Vertica' },
    { name: 'ClickHouse' },
    { name: 'InfluxDB' },
    { name: 'TimescaleDB' },
    { name: 'Cosmos DB', aliases: ['cosmosdb'] },
    { name: 'HBase' },
    { name: 'Pinecone' },
    { name: 'Weaviate' },
    { name: 'pgvector' },
    { name: 'Database design', aliases: ['data modeling', 'schema design'] },
    { name: 'Query optimization' },

    // --- Cloud ---
    { name: 'AWS', aliases: ['amazon web services'] },
    { name: 'Azure', aliases: ['microsoft azure'] },
    { name: 'Google Cloud', aliases: ['gcp', 'google cloud platform'] },
    { name: 'EC2' },
    { name: 'S3' },
    { name: 'AWS Lambda', aliases: ['lambda'] },
    { name: 'ECS' },
    { name: 'EKS' },
    { name: 'Fargate' },
    { name: 'CloudFormation' },
    { name: 'CloudWatch' },
    { name: 'API Gateway' },
    { name: 'SQS' },
    { name: 'SNS' },
    { name: 'Step Functions' },
    { name: 'IAM' },
    { name: 'RDS' },
    { name: 'Azure Functions' },
    { name: 'Azure DevOps' },
    { name: 'GKE' },
    { name: 'Cloud Run' },
    { name: 'Heroku' },
    { name: 'DigitalOcean' },
    { name: 'Cloudflare' },
    { name: 'Vercel' },
    { name: 'Netlify' },
    { name: 'OpenStack' },
    { name: 'VMware' },
    { name: 'Cloud architecture' },
    { name: 'Cost optimization', aliases: ['finops'] },

    // --- DevOps and platform ---
    { name: 'Docker' },
    { name: 'Kubernetes', aliases: ['k8s'] },
    { name: 'Helm' },
    { name: 'Terraform' },
    { name: 'Pulumi' },
    { name: 'Ansible' },
    { name: 'Chef' },
    { name: 'Puppet' },
    { name: 'Vagrant' },
    { name: 'Jenkins' },
    { name: 'GitHub Actions' },
    { name: 'GitLab CI', aliases: ['gitlab ci/cd'] },
    { name: 'CircleCI' },
    { name: 'Travis CI' },
    { name: 'TeamCity' },
    { name: 'Bamboo' },
    { name: 'Argo CD', aliases: ['argocd'] },
    { name: 'Flux' },
    { name: 'Spinnaker' },
    { name: 'Nginx' },
    { name: 'Apache HTTP Server', aliases: ['apache httpd'] },
    { name: 'HAProxy' },
    { name: 'Istio' },
    { name: 'Envoy' },
    { name: 'Consul' },
    { name: 'Vault' },
    { name: 'Prometheus' },
    { name: 'Grafana' },
    { name: 'Datadog' },
    { name: 'New Relic' },
    { name: 'Splunk' },
    { name: 'ELK Stack', aliases: ['elk'] },
    { name: 'Logstash' },
    { name: 'Kibana' },
    { name: 'PagerDuty' },
    { name: 'Sentry' },
    { name: 'OpenTelemetry' },
    { name: 'Jaeger' },
    { name: 'CI/CD', aliases: ['continuous integration', 'continuous delivery', 'continuous deployment'] },
    { name: 'Infrastructure as Code', aliases: ['iac'] },
    { name: 'Site Reliability Engineering', aliases: ['sre'] },
    { name: 'Linux' },
    { name: 'Unix' },
    { name: 'Windows Server' },
    { name: 'Git' },
    { name: 'GitHub' },
    { name: 'GitLab' },
    { name: 'Bitbucket' },
    { name: 'Subversion', aliases: ['svn'] },
    { name: 'Maven' },
    { name: 'Gradle' },
    { name: 'npm' },
    { name: 'Yarn' },
    { name: 'pnpm' },
    { name: 'pip' },
    { name: 'Poetry' },
    { name: 'Bazel' },
    { name: 'Make', aliases: ['makefile'] },
    { name: 'Networking', aliases: ['tcp/ip', 'dns', 'load balancing'] },

    // --- Data and machine learning ---
    { name: 'Kafka', aliases: ['apache kafka'] },
    { name: 'RabbitMQ' },
    { name: 'ActiveMQ' },
    { name: 'Pulsar' },
    { name: 'Kinesis' },
    { name: 'Flink' },
    { name: 'Spark', aliases: ['apache spark', 'pyspark'] },
    { name: 'Hadoop' },
    { name: 'Hive' },
    { name: 'MapReduce' },
    { name: 'Airflow', aliases: ['apache airflow'] },
    { name: 'Dagster' },
    { name: 'Prefect' },
    { name: 'dbt' },
    { name: 'NiFi' },
    { name: 'Informatica' },
    { name: 'Talend' },
    { name: 'SSIS' },
    { name: 'Pandas' },
    { name: 'NumPy' },
    { name: 'SciPy' },
    { name: 'scikit-learn', aliases: ['sklearn', 'scikit learn'] },
    { name: 'TensorFlow' },
    { name: 'PyTorch' },
    { name: 'Keras' },
    { name: 'XGBoost' },
    { name: 'LightGBM' },
    { name: 'Hugging Face', aliases: ['huggingface', 'transformers'] },
    { name: 'LangChain' },
    { name: 'OpenCV' },
    { name: 'NLTK' },
    { name: 'spaCy' },
    { name: 'MLflow' },
    { name: 'Kubeflow' },
    { name: 'SageMaker' },
    { name: 'Tableau' },
    { name: 'Power BI', aliases: ['powerbi'] },
    { name: 'Looker' },
    { name: 'Qlik', aliases: ['qlikview'] },
    { name: 'Superset' },
    { name: 'Jupyter' },
    { name: 'ETL', aliases: ['elt'] },
    { name: 'Data warehousing', aliases: ['data warehouse'] },
    { name: 'Data pipelines', aliases: ['data pipeline'] },
    { name: 'Machine learning', aliases: ['ml'] },
    { name: 'Deep learning' },
    { name: 'NLP', aliases: ['natural language processing'] },
    { name: 'Computer vision' },
    { name: 'LLMs', aliases: ['llm', 'large language model', 'large language models'] },
    { name: 'RAG', aliases: ['retrieval augmented generation', 'retrieval-augmented generation'] },
    { name: 'Generative AI', aliases: ['gen ai', 'genai'] },
    { name: 'Reinforcement learning' },
    { name: 'Statistics', aliases: ['statistical analysis'] },
    { name: 'A/B testing', aliases: ['ab testing', 'experimentation'] },
    { name: 'Data analysis', aliases: ['data analytics'] },
    { name: 'Feature engineering' },
    { name: 'Model deployment', aliases: ['mlops'] },

    // --- Testing and quality ---
    { name: 'JUnit' },
    { name: 'TestNG' },
    { name: 'Mockito' },
    { name: 'pytest' },
    { name: 'Jest' },
    { name: 'Mocha' },
    { name: 'Jasmine' },
    { name: 'Vitest' },
    { name: 'Cypress' },
    { name: 'Playwright' },
    { name: 'Selenium' },
    { name: 'Puppeteer' },
    { name: 'Appium' },
    { name: 'Cucumber' },
    { name: 'Postman' },
    { name: 'JMeter' },
    { name: 'LoadRunner' },
    { name: 'SonarQube' },
    { name: 'TDD', aliases: ['test driven development', 'test-driven development'] },
    { name: 'BDD', aliases: ['behavior driven development'] },
    { name: 'Unit testing' },
    { name: 'Integration testing' },
    { name: 'Performance testing', aliases: ['load testing'] },
    { name: 'Test automation', aliases: ['automated testing'] },

    // --- Security and identity ---
    { name: 'OAuth', aliases: ['oauth2', 'oauth 2.0'] },
    { name: 'SAML' },
    { name: 'OpenID Connect', aliases: ['oidc'] },
    { name: 'JWT' },
    { name: 'SSO', aliases: ['single sign-on', 'single sign on'] },
    { name: 'LDAP' },
    { name: 'Active Directory' },
    { name: 'Kerberos' },
    { name: 'TLS', aliases: ['ssl'] },
    { name: 'PKI' },
    { name: 'Penetration testing', aliases: ['pen testing'] },
    { name: 'OWASP' },
    { name: 'SIEM' },
    { name: 'Zero Trust' },
    { name: 'Encryption', aliases: ['cryptography'] },
    { name: 'Okta' },
    { name: 'Auth0' },
    { name: 'Keycloak' },
    { name: 'Threat modeling' },
    { name: 'SOC 2', aliases: ['soc2'] },
    { name: 'HIPAA' },
    { name: 'GDPR' },
    { name: 'PCI DSS', aliases: ['pci-dss'] },

    // --- Architecture and practice ---
    { name: 'Agile' },
    { name: 'Scrum' },
    { name: 'Kanban' },
    { name: 'SAFe' },
    { name: 'Waterfall' },
    { name: 'Jira' },
    { name: 'Confluence' },
    { name: 'Microservices' },
    { name: 'Event-driven architecture', aliases: ['event driven'] },
    { name: 'Domain-driven design', aliases: ['ddd', 'domain driven design'] },
    { name: 'Design patterns' },
    { name: 'System design' },
    { name: 'Distributed systems' },
    { name: 'Serverless' },
    { name: 'Multithreading', aliases: ['concurrency', 'concurrent programming'] },
    { name: 'Data structures' },
    { name: 'Algorithms' },
    { name: 'Object-oriented programming', aliases: ['oop', 'object oriented'] },
    { name: 'Functional programming' },
    { name: 'Code review' },
    { name: 'Technical writing', aliases: ['documentation'] },
    { name: 'Mentoring' },
    { name: 'Stakeholder management' },
    { name: 'Cross-functional collaboration' },

    // --- Enterprise platforms ---
    { name: 'Salesforce' },
    { name: 'SAP' },
    { name: 'ServiceNow' },
    { name: 'Workday' },
    { name: 'PeopleSoft' },
    { name: 'NetSuite' },
    { name: 'Shopify' },
    { name: 'WordPress' },
    { name: 'Drupal' },
    { name: 'Sitecore' },
    { name: 'Adobe Experience Manager', aliases: ['aem'] },
    { name: 'Contentful' },
    { name: 'Twilio' },
    { name: 'Stripe' },
    { name: 'Segment' },
    { name: 'Snowplow' },
    { name: 'Excel' },
    { name: 'SharePoint' },
    { name: 'Microsoft Dynamics', aliases: ['dynamics 365'] },
    { name: 'Mulesoft' },
    { name: 'Boomi' },
    { name: 'Apigee' },
    { name: 'Kong' },
    { name: 'Camunda' }
  ];

  root.LJS_SKILLS = SKILLS;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SKILLS };
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
